using Microsoft.EntityFrameworkCore;
using SpeedTest.Context.Models;
using SpeedTest.Repository.Interfaces;

namespace SpeedTest.Repository
{
    public class ArticleRepository : IArticleRepository
    {
        public async Task Insert(Article article)
        {
            using (var context = new SpeedTestContext())
            {
                context.Articles.Add(article);
                await context.SaveChangesAsync();
            }
        }

        public async Task Update(Article article)
        {
            using (var context = new SpeedTestContext())
            {
                context.Entry(article).State = EntityState.Modified;
                await context.SaveChangesAsync();
            }
        }

        public async Task Delete(int articleId)
        {
            using (var context = new SpeedTestContext())
            {
                var article = await context.Articles.FindAsync(articleId);
                if(article != null)
                {
                    context.Articles.Remove(article);
                    await context.SaveChangesAsync();
                }
            }
        }

        public async Task<Article> GetOne(int id)
        {
            using (var context = new SpeedTestContext())
            {
                return await context.Articles.FindAsync(id);
            }
        }

        public async Task<IEnumerable<Article>> All()
        {
            using (var context = new SpeedTestContext())
            {
                return await context.Articles.ToListAsync();
            }
        }

        //Generated by copilot
        public async Task<IEnumerable<Article>> Top(int numArticles)
        {
            //list of the 5 most popular articles by article rating
            using (var context = new SpeedTestContext())
            {
                return await context.Articles
                    .OrderByDescending(a => a.ArticleRatings.Average(ar => ar.Rating))
                    .Take(numArticles)
                    .ToListAsync();
            }
        }
    }
}
