using Microsoft.EntityFrameworkCore;
using SpeedTest.Context.Models;
using SpeedTest.Repository.Interfaces;
using SpeedTest.Repository.ViewModels;

namespace SpeedTest.Repository
{
    public class AuthorRepository : IAuthorRepository
    {
        public async Task Insert(Author author)
        {
            using (var context = new SpeedTestContext())
            {
                context.Authors.Add(author);
                await context.SaveChangesAsync();
            }
        }

        public async Task Update(Author author)
        {
            using (var context = new SpeedTestContext())
            {
                context.Entry(author).State = EntityState.Modified;
                await context.SaveChangesAsync();
            }
        }

        public async Task Delete(int authorId)
        {
            using (var context = new SpeedTestContext())
            {
                var Author = await context.Authors.FindAsync(authorId);
                if(Author != null)
                {
                    context.Authors.Remove(Author);
                    await context.SaveChangesAsync();
                }
            }
        }

        public async Task<Author> GetOne(int id)
        {
            using (var context = new SpeedTestContext())
            {
                return await context.Authors.FindAsync(id);
            }
        }

        public async Task<IEnumerable<Author>> All()
        {
            using (var context = new SpeedTestContext())
            {
                return await context.Authors.ToListAsync();
            }
        }

        //Generated by copilot
        public IEnumerable<AuthorRating> Top(int numAuthors)
        {
            //list of the 5 most popular authors by article rating of the article they
            //were the author of
            using (var context = new SpeedTestContext())
            {
                var query = context.ArticleRatings
                    .GroupBy(r => new { r.Article.AuthorId, r.Article.Author.AuthorName })
                    .Select(g => new AuthorRating
                    {
                        AuthorId = g.Key.AuthorId,
                        AuthorName = g.Key.AuthorName,
                        AverageRating = g.Average(x => x.Rating)
                    })
                    .OrderByDescending(x => x.AverageRating)
                    .Take(5)  
                    ;

                var queryString = query.ToQueryString();

                return query.ToList();
            }

        }
    }
}
